name: .NET build

on:
  push:
    paths:
    - src/**
    - .github/workflows/dotnet-build.yaml
  pull_request:
    paths:
    - src/**
    - .github/workflows/dotnet-build.yaml

env:
  config: Release
  csproj: ./src/whistleblower/whistleblower.csproj

jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Local Build
      run: dotnet build --configuration ${config} ${csproj}